export type Lang = "zh" | "en";
export type AlbumType = "solo" | "collab" | "compilation";
export type LocalizedText = Record<Lang, string>;

export interface Track {
  name: string;
  spotifyTrackId?: string;
}

export interface TimelineEra {
  id: string;
  range: string;
  title: LocalizedText;
  body: LocalizedText;
  albumIds?: string[];
}

export interface Album {
  id: string;
  title: string;
  year: number;
  type: AlbumType;
  credit: string;
  palette: { primary: string; secondary: string; text: string };
  cover: string;
  heroImage?: string;
  summary: LocalizedText;
  note?: LocalizedText;
  tracks: Track[];
  links: { apple: string; spotify: string };
  sourceUrls: string[];
  spineDesign?: string;
  titleFont?: string;
  titleColor?: string;
  spineColor?: string;
  titleBold?: boolean;
  titleUpper?: boolean;
  ratings?: {
    pitchfork?: number;
    metacritic?: number;
    aoty?: number;
  };
  spotifyAlbumId?: string;
}

const sourceDiscography = "https://en.wikipedia.org/wiki/Kanye_West_albums_discography";
const sourceFandom = "https://kanyewest.fandom.com/wiki/Discography";
const musicLinks = (query: string) => ({
  apple: `https://music.apple.com/us/search?term=${encodeURIComponent(query)}`,
  spotify: `https://open.spotify.com/search/${encodeURIComponent(query)}`,
});

export const albums: Album[] = [
  {
    id: "college-dropout",
    title: "The College Dropout",
    year: 2004,
    type: "solo",
    credit: "Kanye West",
    palette: { primary: "#7d4025", secondary: "#21140d", text: "#f3dac4" },
    cover: "/assets/covers/college-dropout.jpg",
    heroImage: "/assets/heroes/college-dropout.png",
    summary: {
      zh: "从制作人身份走向前台的起点。灵魂采样、校园熊形象、阶层焦虑与自我神话在这里第一次合成完整世界观。",
      en: "The producer steps into the foreground: soul samples, dropout iconography, class anxiety, and self-mythology form the first complete world.",
    },
    tracks: [
      { name: "Intro", spotifyTrackId: "7lIr3vVhpDkU5mQEDcnA0S" },
      { name: "We Don't Care", spotifyTrackId: "0IW0qaeyxL5Et4UG2MrJKB" },
      { name: "All Falls Down", spotifyTrackId: "5SkRLpaGtvYPhw02vZhQQ9" },
      { name: "Spaceship", spotifyTrackId: "1ko2NuvWlQdxtNRc8QQzmT" },
      { name: "Jesus Walks", spotifyTrackId: "5g1vtHqi9uV7xtYeCcFOBx" },
      { name: "Never Let Me Down", spotifyTrackId: "34j4OxJxKznBs88cjSL2j9" },
      { name: "Get Em High", spotifyTrackId: "5b2FFKC64kxqcfaFnIZxoM" },
      { name: "The New Workout Plan", spotifyTrackId: "1Vp4St7JcXaUoJcIahtf3L" },
      { name: "Slow Jamz", spotifyTrackId: "3A4cpTBPaIQdtPFb5JxtaX" },
      { name: "Through the Wire", spotifyTrackId: "4mmkhcEm1Ljy1U9nwtsxUo" },
      { name: "Family Business", spotifyTrackId: "5DBmXF7QO43Cuy9yqva116" },
      { name: "Last Call", spotifyTrackId: "7iOhWWYjhhQiXzF4o4HhXN" }
    ],
    links: musicLinks("Kanye West The College Dropout"),
    sourceUrls: [sourceDiscography],
    spineDesign: "THE COLLEGE DROPOUT",
    titleFont: "EB Garamond, Georgia, serif",
    titleColor: "#8B5E3C",
    spineColor: "#8B5E3C",
    ratings: { pitchfork: 8.2, metacritic: 87, aoty: 90 },
    spotifyAlbumId: "4Uv86qWpGTxf7fU7lG5X6F",
  },
  {
    id: "late-registration",
    titleColor: "#d4af37",
    title: "Late Registration",
    year: 2005,
    type: "solo",
    credit: "Kanye West",
    palette: { primary: "#5d2b17", secondary: "#0d0907", text: "#f1c391" },
    cover: "/assets/covers/late-registration.jpg",
    heroImage: "/assets/heroes/late-registration.png",
    summary: {
      zh: "管弦乐、灵魂乐和说唱制作被拉进更大的剧场。它把首专的机智扩展为更华丽、更成熟的流行建筑。",
      en: "Orchestration, soul, and rap production expand into a larger theatre, turning the debut's wit into a more ornate pop architecture.",
    },
    tracks: [
      { name: "Wake Up Mr. West", spotifyTrackId: "62KeM7jbmYvzT5FycdiQeS" },
      { name: "Heard 'Em Say", spotifyTrackId: "6yIjtVtnOBeC8SwdVHzAuF" },
      { name: "Touch the Sky", spotifyTrackId: "2dxjKgT0li4qBI3QwuN9Ih" },
      { name: "Gold Digger", spotifyTrackId: "1PS1QMdUqOal0ai3Gt7sDQ" },
      { name: "Drive Slow", spotifyTrackId: "6vB49BJ70zBpDrrAPwdaB8" },
      { name: "Crack Music", spotifyTrackId: "4fRTe59xEeNHT4uyAGsV27" },
      { name: "Roses", spotifyTrackId: "2DHNCWZYmVr1Lv08q5b0kB" },
      { name: "Diamonds from Sierra Leone (Remix)", spotifyTrackId: "34KUIBsIUiPV7oCIzSdDAU" },
      { name: "We Major", spotifyTrackId: "46fk9wjYcPm0sgym2b7EEE" },
      { name: "Hey Mama", spotifyTrackId: "46OFHBw45fNi7QNjSetITR" },
      { name: "Gone", spotifyTrackId: "5RjbFGeWVsCpw8EcE8OrvZ" },
      { name: "Late", spotifyTrackId: "1mFHMzbaECWFaPfoePoEYl" }
    ],
    links: musicLinks("Kanye West Late Registration"),
    sourceUrls: [sourceDiscography],
    spineDesign: "LATE REGISTRATION",
    titleFont: "Cormorant Garamond, Georgia, serif",
    ratings: { pitchfork: 9.5, metacritic: 85, aoty: 90 },
    spotifyAlbumId: "5ll74bqtkcXlKE7wwkMq4g",
  },
  {
    id: "graduation",
    title: "Graduation",
    year: 2007,
    type: "solo",
    credit: "Kanye West",
    palette: { primary: "#7851d8", secondary: "#1b113c", text: "#f5e56b" },
    cover: "/assets/covers/graduation.jpg",
    heroImage: "/assets/heroes/graduation.png",
    summary: {
      zh: "电子合成器、竞技场钩子与村上隆视觉共同把说唱推向体育馆尺度。它明亮、锋利，也标记了博客时代的野心。",
      en: "Synths, stadium hooks, and Takashi Murakami imagery push rap toward arena scale: bright, sharp, and blog-era ambitious.",
    },
    tracks: [
      { name: "Good Morning", spotifyTrackId: "6MXXY2eiWkpDCezVCc0cMH" },
      { name: "Champion", spotifyTrackId: "4UQMOPSUVJVicIQzjAcRRZ" },
      { name: "Stronger", spotifyTrackId: "0j2T0R9dR9qdJYsB7ciXhf" },
      { name: "I Wonder", spotifyTrackId: "7rbECVPkY5UODxoOUVKZnA" },
      { name: "Good Life", spotifyTrackId: "4ZPdLEztrlZqbJkgHNw54L" },
      { name: "Can't Tell Me Nothing", spotifyTrackId: "0mEdbdeRFQwBhN4xfyIeUM" },
      { name: "Barry Bonds", spotifyTrackId: "7387VaiHpOsSIZ5nmjseya" },
      { name: "Flashing Lights", spotifyTrackId: "5TRPicyLGbAF2LGBFbHGvO" },
      { name: "Everything I Am", spotifyTrackId: "0NrtwAmRAdLxua31SzHvXr" },
      { name: "The Glory", spotifyTrackId: "0lWjRSzq5chA9fps3pM8Zr" },
      { name: "Homecoming", spotifyTrackId: "4iz9lGMjU1lXS51oPmUmTe" },
      { name: "Big Brother", spotifyTrackId: "2L47m9erkB5KBZcaqWtYen" }
    ],
    links: musicLinks("Kanye West Graduation"),
    sourceUrls: [sourceDiscography],
    spineDesign: "GRADUATION",
    titleFont: "Anton, Impact, sans-serif",
    titleColor: "#c2185b",
    spineColor: "#c2185b",
    ratings: { pitchfork: 8.7, metacritic: 79, aoty: 86 },
    spotifyAlbumId: "4SZko61aMnmgvNhfhgTuD3",
  },
  {
    id: "808s-heartbreak",
    title: "808s & Heartbreak",
    year: 2008,
    type: "solo",
    credit: "Kanye West",
    palette: { primary: "#b9c7d8", secondary: "#171b21", text: "#f2f7ff" },
    cover: "/assets/covers/808s-heartbreak.jpg",
    heroImage: "/assets/heroes/808s-heartbreak.webp",
    summary: {
      zh: "极简鼓机、Auto-Tune 与哀悼情绪构成冰冷空间。这张专辑把脆弱感变成后来十多年流行说唱的重要语言。",
      en: "Minimal drum machines, Auto-Tune, and grief create a cold room. Vulnerability becomes a language for the next decade of rap and pop.",
    },
    tracks: [
      { name: "Say You Will", spotifyTrackId: "5e5MKPtJuFb8NaeSEyV5gD" },
      { name: "Welcome to Heartbreak", spotifyTrackId: "3F18I7LhWKxlf1PytSoTBH" },
      { name: "Heartless", spotifyTrackId: "4EWCNWgDS8707fNSZ1oaA5" },
      { name: "Amazing", spotifyTrackId: "0m3Ze0cy8qBHSsV2exAfCw" },
      { name: "Love Lockdown", spotifyTrackId: "1kxeWHF9PrCVZHvVskv8lg" },
      { name: "Paranoid", spotifyTrackId: "0w2piYWj1F2bzUftzGJgK9" },
      { name: "RoboCop", spotifyTrackId: "02LAK7qT1wya0klSeNO96f" },
      { name: "Street Lights", spotifyTrackId: "6j8gTlbhj9KJSeypNcNAS9" },
      { name: "Bad News", spotifyTrackId: "1nNPoG2hygEvrFGlHdhvJ9" },
      { name: "See You In My Nightmares", spotifyTrackId: "5zuoz1NBnpoHK6g5sbEH8F" },
      { name: "Coldest Winter", spotifyTrackId: "2RRFTLIglxHgAYQzsSLI4Y" },
      { name: "Pinocchio Story", spotifyTrackId: "6giHsGo1eSYZSXKdNwTC62" }
    ],
    links: musicLinks("Kanye West 808s & Heartbreak"),
    sourceUrls: [sourceDiscography],
    spineDesign: "808s & HEARTBREAK",
    titleFont: "League Gothic, Arial Narrow, sans-serif",
    ratings: { pitchfork: 7.6, metacritic: 75, aoty: 80 },
    spotifyAlbumId: "3WFTGIO6E3Xh4paEOBY9OU",
  },
  {
    id: "mbdtf",
    title: "My Beautiful Dark Twisted Fantasy",
    year: 2010,
    type: "solo",
    credit: "Kanye West",
    palette: { primary: "#7d0714", secondary: "#080305", text: "#ffd7c6" },
    cover: "/assets/covers/mbdtf.jpg",
    heroImage: "/assets/heroes/mbdtf.png",
    summary: {
      zh: "奢华、悔罪、狂妄与自我审判汇成一场巴洛克式说唱歌剧。深红与黑色成为这座宇宙里最浓烈的厅堂。",
      en: "Luxury, confession, arrogance, and self-trial converge into a baroque rap opera: the deepest red chamber in the universe.",
    },
    tracks: [
      { name: "Dark Fantasy", spotifyTrackId: "7yNK27ZTpHew0c55VvIJgm" },
      { name: "Gorgeous", spotifyTrackId: "23SZWX2IaDnxmhFsSLvkG2" },
      { name: "Power", spotifyTrackId: "2gZUPNdnz5Y45eiGxpHGSc" },
      { name: "All of the Lights", spotifyTrackId: "22L7bfCiAkJo5xGSQgmiIO" },
      { name: "Monster", spotifyTrackId: "1ZHYJ2Wwgxes4m8Ba88PeK" },
      { name: "So Appalled", spotifyTrackId: "6K07Ahf6V7CAQn0ikrOztl" },
      { name: "Devil in a New Dress", spotifyTrackId: "1UGD3lW3tDmgZfAVDh6w7r" },
      { name: "Runaway", spotifyTrackId: "3DK6m7It6Pw857FcQftMds" },
      { name: "Hell of a Life", spotifyTrackId: "3rCNmRonlHN1TXQLcG3dSk" },
      { name: "Blame Game", spotifyTrackId: "4EndPA8b6FDWYp1RgsnLEB" },
      { name: "Lost in the World", spotifyTrackId: "2Im64pIz6m0EJKdUe6eZ8r" },
      { name: "Who Will Survive in America", spotifyTrackId: "4e5IPJxSGVWPsaxQzdRseN" }
    ],
    links: musicLinks("Kanye West My Beautiful Dark Twisted Fantasy"),
    sourceUrls: [sourceDiscography],
    spineDesign: "MY BEAUTIFUL DARK TWISTED FANTASY",
    titleFont: "Bodoni Moda, Bodoni MT, Georgia, serif",
    titleBold: true,
    titleColor: "#cc0000",
    spineColor: "#cc0000",
    ratings: { pitchfork: 10.0, metacritic: 94, aoty: 89 },
    spotifyAlbumId: "20r762YmB5HeofjMCiPMLv",
  },
  {
    id: "watch-the-throne",
    title: "Watch the Throne",
    year: 2011,
    type: "collab",
    credit: "Jay-Z & Kanye West",
    palette: { primary: "#c9a34b", secondary: "#0e0a05", text: "#fff0c2" },
    cover: "/assets/covers/watch-the-throne.jpg",
    heroImage: "/assets/covers/watch-the-throne.jpg",
    summary: {
      zh: "皇权、财富、黑人卓越与全球化采样的金色纪念碑。它把合作专辑做成一座自带回声的宫殿。",
      en: "A gold monument to power, wealth, Black excellence, and global samples; a collaborative album built like a palace with echoes.",
    },
    tracks: [
      { name: "No Church in the Wild", spotifyTrackId: "7r6PigmGzlB3YPB7wvBBbi" },
      { name: "Lift Off", spotifyTrackId: "4TRUsIZw92IhJjAtxtiC4e" },
      { name: "Niggas in Paris", spotifyTrackId: "1auxYwYrFRqZP7t3s7w4um" },
      { name: "Otis", spotifyTrackId: "14I61w6cyYUHiV2n28IYdP" },
      { name: "Gotta Have It", spotifyTrackId: "2aqe2NgAwmMlPgtf1MnGoy" },
      { name: "New Day", spotifyTrackId: "0x367gcUm6nsEoMXXFfEMy" },
      { name: "That's My Bitch", spotifyTrackId: "1BMzxGds8WSK39p4y432fl" },
      { name: "Welcome to the Jungle", spotifyTrackId: "0y0imMk6KsO90MaHG4MVAl" },
      { name: "Who Gon Stop Me", spotifyTrackId: "22ngk2DRBy7audIugfYDKd" },
      { name: "Murder to Excellence", spotifyTrackId: "3Gjc2FE6BEMMHURUjlMXvX" },
      { name: "Made in America", spotifyTrackId: "0qM9UF4CbazQ5xa8PCTopE" },
      { name: "Why I Love You", spotifyTrackId: "4bDPr2VAjcfgUDmN9dGOC3" }
    ],
    links: musicLinks("Jay-Z Kanye West Watch the Throne"),
    sourceUrls: [sourceDiscography],
    spineDesign: "WATCH THE THRONE",
    titleFont: "Cinzel, Trajan Pro, serif",
    ratings: { pitchfork: 8.5, metacritic: 75, aoty: 71 },
    spotifyAlbumId: "0OcMap99vLEeGkBCfCwRwS",
  },
  {
    id: "cruel-summer",
    title: "Cruel Summer",
    year: 2012,
    type: "compilation",
    credit: "GOOD Music",
    palette: { primary: "#f4f0e7", secondary: "#111111", text: "#f9f4eb" },
    cover: "/assets/covers/cruel-summer.jpg",
    heroImage: "/assets/heroes/cruel-summer.png",
    summary: {
      zh: "GOOD Music 时代的集团合辑，像一张厂牌宣言。它不属于 Ye 个人专辑序列，却是 YeVerse 17 张口径里的关键支线。",
      en: "A GOOD Music crew statement. It is not a Ye solo album, but it is a key branch in this 17-record YeVerse canon.",
    },
    tracks: [
      { name: "To the World", spotifyTrackId: "4OeQM6VKvF8QQLaqvhP3qo" },
      { name: "Clique", spotifyTrackId: "65rRB2mspD309xE6YimZTl" },
      { name: "Mercy", spotifyTrackId: "671XaUBmifTMXDbZK5CB1M" },
      { name: "New God Flow", spotifyTrackId: "2Fq5o2kLhNssLiRATRcPFT" },
      { name: "The Morning", spotifyTrackId: "6KdwBL0OFecxLc1cSV9WVp" },
      { name: "Cold", spotifyTrackId: "7jCkMZdvs8ABVd7fAHyQHM" },
      { name: "Higher", spotifyTrackId: "3yldvwyhm4WKrPyoJHSx99" },
      { name: "Sin City", spotifyTrackId: "3BkPFyejx6Qf4otNHMvxap" },
      { name: "The One", spotifyTrackId: "6uG4BxL4qqSIOXfEiGdpBf" },
      { name: "Creepers", spotifyTrackId: "6vO5OZ18h33ZO40S9plFDx" },
      { name: "Bliss", spotifyTrackId: "5wDk4aZoWHvO8HAhOkxzZe" },
      { name: "Don't Like", spotifyTrackId: "2rJvc7nSYWBKAuNUMx1Cr2" }
    ],
    links: musicLinks("GOOD Music Cruel Summer"),
    sourceUrls: [sourceDiscography, sourceFandom],
    spineDesign: "CRUEL SUMMER",
    titleFont: "Bebas Neue, Impact, sans-serif",
    ratings: { pitchfork: 6.8, metacritic: 60, aoty: 63 },
    spotifyAlbumId: "0bcOGgwJpwBjfFBTApoqSn",
  },
  {
    id: "yeezus",
    title: "Yeezus",
    year: 2013,
    type: "solo",
    credit: "Kanye West",
    palette: { primary: "#f2f2f2", secondary: "#050505", text: "#ffffff" },
    cover: "/assets/covers/yeezus.jpg",
    heroImage: "/assets/heroes/yeezus.png",
    summary: {
      zh: "工业噪音、极简封面、刺耳合成器和反流行结构。它像一块没有装饰的黑白金属板，冷、硬、冒犯、精准。",
      en: "Industrial noise, a minimal package, abrasive synths, and anti-pop structure: a cold black-and-white metal plate.",
    },
    tracks: [
      { name: "On Sight", spotifyTrackId: "1gqkRc9WtOpnGIqxf2Hvzr" },
      { name: "Black Skinhead", spotifyTrackId: "722tgOgdIbNe3BEyLnejw4" },
      { name: "I Am a God", spotifyTrackId: "0HMCdlOPJkAGlB0MlSWIcO" },
      { name: "New Slaves", spotifyTrackId: "4cAgkb0ifwn0FSHGXnr4F6" },
      { name: "Hold My Liquor", spotifyTrackId: "5nIu0VwPOsjkF61zfevLKh" },
      { name: "I'm In It", spotifyTrackId: "52NmkyHsGsHGb1UX8fTkMg" },
      { name: "Blood on the Leaves", spotifyTrackId: "42GcjriRK6srwHkfbkBqVl" },
      { name: "Guilt Trip", spotifyTrackId: "5nPOM0nFRAJ3XI8xCxNAzO" },
      { name: "Send It Up", spotifyTrackId: "3RKblQNJs8HPvWBgXmq6nn" },
      { name: "Bound 2", spotifyTrackId: "3sNVsP50132BTNlImLx70i" }
    ],
    links: musicLinks("Kanye West Yeezus"),
    sourceUrls: [sourceDiscography],
    spineDesign: "YEEZUS",
    titleFont: "Inter, Helvetica Neue, sans-serif",
    ratings: { pitchfork: 9.5, metacritic: 84, aoty: 84 },
    spotifyAlbumId: "7D2NdGvBHIavgLhmcwhluK",
  },
  {
    id: "life-of-pablo",
    title: "The Life of Pablo",
    year: 2016,
    type: "solo",
    credit: "Kanye West",
    palette: { primary: "#f06a22", secondary: "#120905", text: "#ffe1c4" },
    cover: "/assets/covers/life-of-pablo.jpg",
    heroImage: "/assets/heroes/life-of-pablo.jpg",
    summary: {
      zh: "持续更新的流媒体时代拼贴：福音、家庭、欲望、时装周和未完成感共存。它像一块永远在改稿的橙色公告板。",
      en: "A streaming-era collage of gospel, family, desire, fashion week, and intentional incompletion: an orange board still being revised.",
    },
    tracks: [
      { name: "Ultralight Beam", spotifyTrackId: "1eQBEelI2NCy7AUTerX0KS" },
      { name: "Father Stretch My Hands Pt. 1", spotifyTrackId: "4KW1lqgSr8TKrvBII0Brf8" },
      { name: "Pt. 2", spotifyTrackId: "1Wsbr1d2BouNGk2q92mIj7" },
      { name: "Famous", spotifyTrackId: "19a3JfW8BQwqHWUMbcqSx8" },
      { name: "Feedback", spotifyTrackId: "49fT6owWuknekShh9utsjv" },
      { name: "Highlights", spotifyTrackId: "4qYLPta5HZ36idWiXtqh7B" },
      { name: "Freestyle 4", spotifyTrackId: "6wfzokDylbrJzrJcpnBkcy" },
      { name: "I Love Kanye", spotifyTrackId: "5CGS4UovzA7ftCJkLVXQju" },
      { name: "Waves", spotifyTrackId: "3nAq2hCr1oWsIU54tS98pL" },
      { name: "FML", spotifyTrackId: "30Zcjs7pgEkmJA1lEbGSWT" },
      { name: "Real Friends", spotifyTrackId: "66Q3fAmSX5eHamgbKa9alP" },
      { name: "Wolves", spotifyTrackId: "432hUIl3ISDeytYW5XBQ5h" },
      { name: "30 Hours", spotifyTrackId: "2CHmgtK8OCL28WtIK96u4N" },
      { name: "No More Parties in LA", spotifyTrackId: "0zLClc0emc6qUeV1p5nc99" },
      { name: "Facts (Charlie Heat Version)", spotifyTrackId: "3MnbXlC1N7GdS9M8HzA6no" },
      { name: "Fade", spotifyTrackId: "3cCxoOgfi6hgt8MNteuiiD" },
      { name: "Saint Pablo", spotifyTrackId: "1o0kWPueYo94LIjPYOE5Nf" }
    ],
    links: musicLinks("Kanye West The Life of Pablo"),
    sourceUrls: [sourceDiscography],
    spineDesign: "THE LIFE OF PABLO",
    titleFont: "Inter, Helvetica Neue, sans-serif",
    titleColor: "#ffffff",
    spineColor: "#000000",
    titleUpper: true,
    ratings: { pitchfork: 9.0, metacritic: 75, aoty: 84 },
    spotifyAlbumId: "7gsWAHLeT0w7es6FofOXk1",
  },
  {
    id: "ye",
    title: "Ye",
    year: 2018,
    type: "solo",
    credit: "Kanye West",
    palette: { primary: "#8aa0a7", secondary: "#101719", text: "#e9f1f2" },
    cover: "/assets/covers/ye.jpg",
    heroImage: "/assets/heroes/ye.jpg",
    summary: {
      zh: "七首歌的山地独白，短、暴露、像一张情绪切片。它把自画像压缩到近乎手写便签的尺度。",
      en: "A seven-song mountain monologue: brief, exposed, and compressed to the scale of a handwritten note.",
    },
    tracks: [
      { name: "I Thought About Killing You", spotifyTrackId: "0yhxBvedRdGxsPZHJNI4VA" },
      { name: "Yikes", spotifyTrackId: "1qsHYUd2c1wFGcn7e63QmG" },
      { name: "All Mine", spotifyTrackId: "3U21A07gAloCc4P7J8rxcn" },
      { name: "Wouldn't Leave", spotifyTrackId: "1nGoy0cEj0extAwXYNYTWd" },
      { name: "No Mistakes", spotifyTrackId: "35KV2Nuib6jPMVN00O8iba" },
      { name: "Ghost Town", spotifyTrackId: "7vgTNTaEz3CsBZ1N4YQalM" },
      { name: "Violent Crimes", spotifyTrackId: "3s7MCdXyWmwjdcWh7GWXas" }
    ],
    links: musicLinks("Kanye West Ye"),
    sourceUrls: [sourceDiscography],
    spineDesign: "ye",
    titleFont: "Caveat, cursive",
    titleColor: "#2ecc71",
    ratings: { pitchfork: 7.1, metacritic: 64, aoty: 79 },
    spotifyAlbumId: "2Ek1q2haOnxVqhvVKqMvJe",
  },
  {
    id: "kids-see-ghosts",
    title: "Kids See Ghosts",
    year: 2018,
    type: "collab",
    credit: "Kids See Ghosts",
    palette: { primary: "#d65832", secondary: "#16100c", text: "#ffd4ba" },
    cover: "/assets/covers/kids-see-ghosts.jpg",
    heroImage: "/assets/heroes/kids-see-ghosts.webp",
    summary: {
      zh: "与 Kid Cudi 的七首治愈仪式。摇滚、迷幻、动漫式封面和心理阴影在短篇幅里达成罕见平衡。",
      en: "A seven-track healing ritual with Kid Cudi where rock, psychedelia, animated cover art, and shadow find rare balance.",
    },
    tracks: [
      { name: "Feel the Love", spotifyTrackId: "3aUFrxO1B8EW63QchEl3wX" },
      { name: "Fire", spotifyTrackId: "7oHkit3F3vimtsBbnZkU0G" },
      { name: "4th Dimension", spotifyTrackId: "6JyEh4kl9DLwmSAoNDRn5b" },
      { name: "Freeee (Ghost Town Pt. 2)", spotifyTrackId: "7GRTrWsP3yo2Fx8umJfA1X" },
      { name: "Reborn", spotifyTrackId: "4RVbK6cV0VqWdpCDcx3hiT" },
      { name: "Kids See Ghosts", spotifyTrackId: "2I3dW2dCBZAJGj5X21E53k" },
      { name: "Cudi Montage", spotifyTrackId: "4kUZvXB3LC3an3HX6h0s17" }
    ],
    links: musicLinks("Kids See Ghosts album"),
    sourceUrls: [sourceDiscography],
    spineDesign: "KIDS SEE GHOSTS",
    titleFont: "Zen Old Mincho, serif",
    titleColor: "#00bcd4",
    ratings: { pitchfork: 8.4, metacritic: 84, aoty: 85 },
    spotifyAlbumId: "6pwuKxMUkNg673KETsXPUV",
  },
  {
    id: "jesus-is-king",
    title: "Jesus Is King",
    year: 2019,
    type: "solo",
    credit: "Kanye West",
    palette: { primary: "#2457d6", secondary: "#050814", text: "#d9e8ff" },
    cover: "/assets/covers/jesus-is-king.jpg",
    heroImage: "/assets/heroes/jesus-is-king.png",
    summary: {
      zh: "福音转向的正式声明，合唱、信仰语言与蓝色极简封面组成新的精神秩序。",
      en: "A formal gospel turn, placing choir, devotional language, and a blue minimal cover inside a new spiritual order.",
    },
    tracks: [
      { name: "Every Hour", spotifyTrackId: "1WnqWQcWcuQbVzgE7ecfCY" },
      { name: "Selah", spotifyTrackId: "39JRmdKFka1Oe09FoOCPI4" },
      { name: "Follow God", spotifyTrackId: "2QpGZOhTCHHiKmpSO9FW4h" },
      { name: "Closed on Sunday", spotifyTrackId: "3JWiDGQX2eTlFvKj3Yssj3" },
      { name: "On God", spotifyTrackId: "2SasoXZyv82yYgHiVOvxQn" },
      { name: "Everything We Need", spotifyTrackId: "24bnCCysWnbNRNUT4LpHcP" },
      { name: "Water", spotifyTrackId: "454Epa1vrCGFddHXKyC1kb" },
      { name: "God Is", spotifyTrackId: "6xRWoYwfwIKnT8bQGzKbxR" },
      { name: "Hands On", spotifyTrackId: "7r6aR2f57resC5r93LwMfK" },
      { name: "Use This Gospel", spotifyTrackId: "0oPOuDmmkVp3h6puekhs6P" },
      { name: "Jesus Is Lord", spotifyTrackId: "7sBgFMWqDWQgrsNSpIBoe8" }
    ],
    links: musicLinks("Kanye West Jesus Is King"),
    sourceUrls: [sourceDiscography],
    spineDesign: "JESUS IS KING",
    titleFont: "Fraunces, Georgia, serif",
    titleColor: "#d4af37",
    ratings: { pitchfork: 7.2, metacritic: 53, aoty: 55 },
    spotifyAlbumId: "0FgZKfoU2Br5sHOfvZKTI9",
  },
  {
    id: "donda",
    title: "Donda",
    year: 2021,
    type: "solo",
    credit: "Kanye West",
    palette: { primary: "#151515", secondary: "#000000", text: "#f0f0f0" },
    cover: "/assets/covers/donda.jpg",
    heroImage: "/assets/heroes/donda.jpg",
    summary: {
      zh: "以母亲之名命名的黑色纪念碑。体育场试听、祈祷、空白封面和超长曲目让它像一场公共追思仪式。",
      en: "A black monument named for his mother, shaped by stadium listening events, prayer, a blank cover, and public mourning.",
    },
    tracks: [
      { name: "Donda Chant", spotifyTrackId: "7eSSmgq26BXr7xay3WKjfi" },
      { name: "Jail", spotifyTrackId: "6d8HN8MqqbqrEUI2bvx0aG" },
      { name: "God Breathed", spotifyTrackId: "5JaSg0AYyAMMLjyGGDrrCm" },
      { name: "Off the Grid", spotifyTrackId: "6LNoArVBBVZzUTUiAX2aKO" },
      { name: "Hurricane", spotifyTrackId: "6Hfu9sc7jvv6coyy2LlzBF" },
      { name: "Praise God", spotifyTrackId: "0WSEq9Ko4kFPt8yo3ICd6T" },
      { name: "Jonah", spotifyTrackId: "35acXjupfWHgtchiS6yAjC" },
      { name: "Ok Ok", spotifyTrackId: "5LuXsO34x6KVlL8OWsxRqk" },
      { name: "Junya", spotifyTrackId: "1jgcODbfAL3tV7tikF6n1j" },
      { name: "Believe What I Say", spotifyTrackId: "0JuSGEldfovcc8IS9va1wa" },
      { name: "24", spotifyTrackId: "68RhNM8ehkarnEKnCkqlsp" },
      { name: "Moon", spotifyTrackId: "7CC6UbCs4iGsePSzFxYxNn" },
      { name: "Heaven and Hell", spotifyTrackId: "2Y40huo5ewaKYxsFintYtF" },
      { name: "Donda", spotifyTrackId: "4jkwu5KQbXXrbAZzVmt5fE" },
      { name: "Keep My Spirit Alive", spotifyTrackId: "7EagormFign5ag6f16ua3I" },
      { name: "Jesus Lord", spotifyTrackId: "1LwdWIbfuqlOo8vlHxkyna" },
      { name: "New Again", spotifyTrackId: "75QktuEju5vz9lyXiLaUao" },
      { name: "Lord I Need You", spotifyTrackId: "5Iq6pIudd4KfuxZqf8872b" },
      { name: "Pure Souls", spotifyTrackId: "5aqUqSq0SqGBAqEn27PEzc" },
      { name: "Come to Life", spotifyTrackId: "5xvXeuxISyXJDRbZZf4uzd" },
      { name: "No Child Left Behind", spotifyTrackId: "3hd6zLhnTlbJ8PupYt3cAI" },
      { name: "Jail pt 2", spotifyTrackId: "2H8jWuNmluerTEsuh8Gu6y" },
      { name: "Ok Ok pt 2", spotifyTrackId: "5ad5uryyzVWs95bK3myGkw" },
      { name: "Junya pt 2", spotifyTrackId: "2auYgZ1GcTkWj2bOaE2Wwm" },
      { name: "Jesus Lord pt 2", spotifyTrackId: "360VkSTITvF55weIKoaNTw" }
    ],
    links: musicLinks("Kanye West Donda"),
    sourceUrls: [sourceDiscography],
    spineDesign: "DONDA",
    titleFont: "Inter, Helvetica Neue, sans-serif",
    titleColor: "#888888",
    spineColor: "#888888",
    ratings: { pitchfork: 6.0, metacritic: 53, aoty: 72 },
    spotifyAlbumId: "5CnpZV3q5BcESefcB3WJmz",
  },
  {
    id: "donda-2",
    title: "Donda 2",
    year: 2022,
    type: "solo",
    credit: "Kanye West",
    palette: { primary: "#2e2e2e", secondary: "#050505", text: "#f2f2f2" },
    cover: "/assets/covers/donda-2.jpg",
    heroImage: "/assets/heroes/donda-2.png",
    note: {
      zh: "特殊发行：最初通过 Stem Player 发布，站内以正式 solo 口径收录并标注状态。",
      en: "Special release: initially issued through Stem Player; included here as a solo record with release context noted.",
    },
    summary: {
      zh: "一张带有未完成感和设备绑定历史的续章。它在 YeVerse 中更像一间半开放的房间，保留过程、缺口和争议状态。",
      en: "A sequel marked by unfinished edges and device-linked release history; an open room preserving process and ambiguity.",
    },
    tracks: [
      { name: "True Love", spotifyTrackId: "3WbuQIjkR1mIKdwSNlgqpp" },
      { name: "Broken Road", spotifyTrackId: "4RXIqq6AWKGQIEXd9il5mB" },
      { name: "Get Lost", spotifyTrackId: "4lUBWLqTFEWx3X6qcjWN2A" },
      { name: "Too Easy", spotifyTrackId: "5JDu5HkUyhcwJHU69ysMvD" },
      { name: "Security", spotifyTrackId: "005Xv5eX9qBquZFVKvRt0E" },
      { name: "We Did It Kid" },
      { name: "Pablo" },
      { name: "Louie Bags", spotifyTrackId: "5bu1Sbx3E2nNHzQUYXeAAj" },
      { name: "Happy" },
      { name: "Sci Fi", spotifyTrackId: "3OEvHAJQiJSxw076rUF1SN" },
      { name: "Selfish", spotifyTrackId: "1u1rZu5iTVoNtddc4yqvn4" },
      { name: "Lord Lift Me Up", spotifyTrackId: "1RopXkbl5fE7gf7fjQIKRf" },
      { name: "City of Gods", spotifyTrackId: "1yJqk94FvUxZ7F3SWhcwHz" },
      { name: "First Time in a Long Time", spotifyTrackId: "7aUzsxDB0DYz7IHX83b2b4" }
    ],
    links: musicLinks("Kanye West Donda 2"),
    sourceUrls: [sourceDiscography],
    spineDesign: "DONDA 2",
    titleFont: "Archivo Narrow, Arial Narrow, sans-serif",
    titleColor: "#888888",
    spineColor: "#888888",
    ratings: { pitchfork: 4.0, metacritic: 46, aoty: 33 },
    spotifyAlbumId: "1ZkGNUz1un0b3Z7EsJl3ci",
  },
  {
    id: "vultures-1",
    title: "Vultures 1",
    year: 2024,
    type: "collab",
    credit: "¥$",
    palette: { primary: "#1b1b1b", secondary: "#050505", text: "#ececec" },
    cover: "/assets/covers/vultures-1.png",
    heroImage: "/assets/heroes/vultures-1.jpg",
    summary: {
      zh: "Ye 与 Ty Dolla Sign 的 ¥$ 章节开场。黑色、裸露、俱乐部低频和争议后的再组织构成新的阵列。",
      en: "The opening ¥$ chapter with Ty Dolla Sign: black surfaces, club low-end, and post-controversy reassembly.",
    },
    tracks: [
      { name: "Stars", spotifyTrackId: "5ogdIq5F70xEPB3kwiiecr" },
      { name: "Keys to My Life", spotifyTrackId: "4iVmy1j5C3XNxpN11RXRaO" },
      { name: "Paid", spotifyTrackId: "1OFgEELgwfTOt3WcBuOPxk" },
      { name: "Talking", spotifyTrackId: "2os3F2ZKbj02ZWXWAdWGFD" },
      { name: "Back to Me", spotifyTrackId: "3g9UquSEBErZiXSDa02YfG" },
      { name: "Hoodrat", spotifyTrackId: "0Ah7O76JL0pyn84jI7NPbr" },
      { name: "Do It", spotifyTrackId: "1oNaDXXu9I4UCJ8Fh0Hfjg" },
      { name: "Paperwork", spotifyTrackId: "2jf0ooqmXMqaGqh0bdYsHR" },
      { name: "Burn", spotifyTrackId: "7BPadP3q9qwMkho3IMPU99" },
      { name: "Fuk Sumn", spotifyTrackId: "0cbVD7WpHVdHUKwoolzhCZ" },
      { name: "Vultures", spotifyTrackId: "3w9WvHLKSXOsW6aAw0yr1n" },
      { name: "Carnival", spotifyTrackId: "2McT2fkH0VDqPsbiB9HWPq" },
      { name: "Beg Forgiveness", spotifyTrackId: "2anbsZVE7y9yhI4KD7QYI0" },
      { name: "Problematic", spotifyTrackId: "7wOpdeL1e8nsK5fQwj40Ox" },
      { name: "King", spotifyTrackId: "0KXIsj1KjSNlGvNora6BA4" }
    ],
    links: musicLinks("¥$ Vultures 1"),
    sourceUrls: [sourceDiscography],
    spineDesign: "VULTURES",
    titleFont: "Pirata One, cursive",
    titleColor: "#6B4226",
    spineColor: "#6B4226",
    ratings: { pitchfork: 5.8, metacritic: 52, aoty: 54 },
    spotifyAlbumId: "4DOsPwJtokv6HEifZ6t5j6",
  },
  {
    id: "vultures-2",
    title: "Vultures 2",
    year: 2024,
    type: "collab",
    credit: "¥$",
    palette: { primary: "#111111", secondary: "#000000", text: "#f4f4f4" },
    cover: "/assets/covers/vultures-2.jpg",
    heroImage: "/assets/heroes/vultures-2.png",
    summary: {
      zh: "¥$ 第二章继续把夜色、低频与碎片化流媒体发行放在一起。站内先保留为可继续扩展的黑色房间。",
      en: "The second ¥$ chapter continues through night tones, low-end, and fragmented streaming-era release patterns.",
    },
    tracks: [
      { name: "Slide", spotifyTrackId: "5MGMXOhVvwzCjFgdQsFokR" },
      { name: "Time Moving Slow", spotifyTrackId: "0JgassGI6jNxpX82jGpcuJ" },
      { name: "Field Trip", spotifyTrackId: "7vv89PswQvqGKCGJ1rw5on" },
      { name: "Fried", spotifyTrackId: "4Qay2jEWJYjXmJ8eNOGtaD" },
      { name: "Isabella", spotifyTrackId: "36XrocrUkmem00MPm2kIst" },
      { name: "Promotion", spotifyTrackId: "6bSfeCXlUaGa3eWCy5qPTb" },
      { name: "530", spotifyTrackId: "2tPNj9sUt3FbjEUqBzZazv" },
      { name: "Dead", spotifyTrackId: "488lIy4J0jJdPUiWqa0doB" },
      { name: "Forever Rolling", spotifyTrackId: "1MTpRBLniy6298BCdyKUfQ" },
      { name: "Bomb", spotifyTrackId: "2kgxyflhiicDbF8SDrBxqy" },
      { name: "River", spotifyTrackId: "5RzSnxqTx4vYEp9re5E0ud" },
      { name: "Forever", spotifyTrackId: "1Cxq3u0RQ0tEBbVofZ9Mma" },
      { name: "Husband", spotifyTrackId: "6LHeisjoP8eHrtu45UbTPO" },
      { name: "Lifestyle", spotifyTrackId: "40FRxwg8SEMO3fbMjFfphU" },
      { name: "Sky City", spotifyTrackId: "7a0tTD7xdvKsNcJfMIDWp4" },
      { name: "My Soul", spotifyTrackId: "3bTkWuPGJ1ueGXBHWVUwAI" }
    ],
    links: musicLinks("¥$ Vultures 2"),
    sourceUrls: [sourceDiscography],
    spineDesign: "VULTURES 2",
    titleFont: "IBM Plex Sans Condensed, Arial Narrow, sans-serif",
    titleColor: "#ffffff",
    ratings: { pitchfork: 4.0, metacritic: 40, aoty: 37 },
    spotifyAlbumId: "5RV2TNyjylqWJNxQyHBTeJ",
  },
  {
    id: "bully",
    title: "Bully",
    year: 2026,
    type: "solo",
    credit: "Ye",
    palette: { primary: "#bdb8aa", secondary: "#0b0b09", text: "#f1eadb" },
    cover: "/assets/covers/bully.jpg",
    heroImage: "/assets/heroes/bully.png",
    summary: {
      zh: "争议声中最克制的一次回归。制作回到早期 Ye 的精密度，却在歌词与情感密度上留下空洞。评论两极分化——有人称之为「十年来第一张好专辑」，也有人视其为「光鲜的空壳」。混乱与内省的张力贯穿始终。",
      en: "The most restrained return amid chaos. Production recovers early-Ye precision, yet the writing leaves emotional gaps. Critics split: some called it his first good album in a decade, others a glossy shell. Tension between chaos and introspection runs throughout.",
    },
    tracks: [
      { name: "King", spotifyTrackId: "4LP6bmyAxdMNrqUrMpaVQ8" },
      { name: "This a Must", spotifyTrackId: "41e8XO5tcG6Uesk2FhdsWm" },
      { name: "Father", spotifyTrackId: "5pfn68duSmBKo4FhYknOms" },
      { name: "All the Love", spotifyTrackId: "2SjnvpedDUU0Ga69bxnoCa" },
      { name: "Punch Drunk", spotifyTrackId: "4bWZz15GR1EE8E8x23rDWV" },
      { name: "Whatever Works", spotifyTrackId: "7GVuAK4EmYP7gvlXA4JXqU" },
      { name: "Mama's Favorite", spotifyTrackId: "25fLIFbAV7zBetOH077pDl" },
      { name: "Sisters and Brothers", spotifyTrackId: "1FpjiEapAG8XJdVSI0tvdc" },
      { name: "Bully", spotifyTrackId: "6KhDb86ThnlKirRw1UBZGb" },
      { name: "Highs and Lows", spotifyTrackId: "565G1vHZu2xoxrnTyF06Qw" },
      { name: "I Can't Wait", spotifyTrackId: "163l4Itf8oDEK7ZYdVm22N" },
      { name: "White Lines", spotifyTrackId: "3bbjDFVu9BtFtGD2fZpVfz" },
      { name: "Circles", spotifyTrackId: "1udGa2Ww3YIVSp5X4OMHFQ" },
      { name: "Preacher Man", spotifyTrackId: "0fD7KBtQgPR1YCtuPAsyZJ" },
      { name: "Beauty and the Beast", spotifyTrackId: "6pxHjkpwGmg97Yn5HcwNTn" },
      { name: "Damn", spotifyTrackId: "4dm2VMjIs1JlGZp2TePJaE" },
      { name: "Last Breath", spotifyTrackId: "13CvK7typ0qYle19p9Vahn" },
      { name: "This One Here", spotifyTrackId: "7uGrdyEErKPSA3oiJQHxQ6" }
    ],
    links: musicLinks("Ye Bully album"),
    sourceUrls: [sourceDiscography, sourceFandom],
    spineDesign: "BULLY",
    titleFont: "Roboto Condensed, Arial Narrow, sans-serif",
    titleColor: "#888888",
    spineColor: "#888888",
    ratings: { pitchfork: 3.4, metacritic: 55, aoty: 65 },
    spotifyAlbumId: "5poA9SAx0Xiz1cf17fWBLS",
  },
];

export const timelineEras: TimelineEra[] = [
  {
    id: "early-life",
    range: "1977 – 1997",
    title: { zh: "Early Life", en: "Early Life" },
    body: {
      zh: "出生于亚特兰大，成长于芝加哥。母亲 Donda West 是英语教授，父亲 Ray West 是前黑豹党成员。10 岁随母亲赴南京担任富布赖特学者。少年时期开始写诗、说唱、制作 beats。师从制作人 No I.D.，进入芝加哥美国艺术学院后转入芝加哥州立大学，20 岁退学追求音乐。2002 年车祸下颌碎裂，戴着钢丝录制 Through the Wire。",
      en: "Born Kanye Omari West in Atlanta, Georgia in 1977. Raised primarily in Chicago after his parents divorced. His mother Donda West was an English professor. His father Ray West worked as a photojournalist. Developed interests in poetry, visual art, music production, and rap during childhood.",
    },
  },
  {
    id: "roc-a-fella",
    range: "1996 – 2002",
    title: { zh: "Early Work & Roc-A-Fella", en: "Early Work & Roc-A-Fella" },
    body: {
      zh: "1990 年代中期在芝加哥开始制作 beats。与本地艺人和 Go-Getters 合作。通过 Roc-A-Fella Records 获得认可。为 Jay-Z 的 The Blueprint 制作。2002 年车祸后录制 Through the Wire。",
      en: "Started producing beats in Chicago in the mid-1990s. Worked with local artists and the Go-Getters. Earned recognition through Roc-A-Fella Records. Produced for Jay-Z's The Blueprint. Recorded 'Through the Wire' after a near-fatal 2002 car accident.",
    },
  },
  {
    id: "college-era",
    range: "2003 – 2006",
    title: { zh: "The College Dropout / Late Registration", en: "The College Dropout / Late Registration" },
    body: {
      zh: "2004 年发行 The College Dropout。专辑确立了他作为说唱歌手和制作人的双重身份。Late Registration 以管弦乐制作扩展了他的声音。这个时代引入了标志性的 Dropout Bear 形象。",
      en: "Released The College Dropout in 2004. The album established him as both rapper and producer. Late Registration expanded his sound with orchestral production. This era introduced the iconic Dropout Bear imagery.",
    },
    albumIds: ["college-dropout", "late-registration"],
  },
  {
    id: "graduation-808s",
    range: "2007 – 2009",
    title: { zh: "Graduation / 808s & Heartbreak", en: "Graduation / 808s & Heartbreak" },
    body: {
      zh: "Graduation 在 2007 年取得重大商业成功。Stronger 将电子音乐影响引入主流嘻哈。母亲 Donda West 去世后，他发行了 808s & Heartbreak。这张专辑影响了一代旋律说唱艺术家。2009 年 VMA 事件成为一个重大文化转折点。",
      en: "Graduation became a major commercial success in 2007. Stronger introduced electronic influences into mainstream hip-hop. After the death of Donda West, he released 808s & Heartbreak. The album influenced a generation of melodic rap artists. The 2009 VMAs incident became a major cultural turning point.",
    },
    albumIds: ["graduation", "808s-heartbreak"],
  },
  {
    id: "dark-fantasy",
    range: "2010 – 2012",
    title: { zh: "Dark Fantasy / Watch the Throne", en: "Dark Fantasy / Watch the Throne" },
    body: {
      zh: "在夏威夷创作 My Beautiful Dark Twisted Fantasy。发行 Runaway 和 GOOD Fridays 系列。与 Jay-Z 合作 Watch the Throne。通过 Cruel Summer 扩展了 GOOD Music 集体。",
      en: "Created My Beautiful Dark Twisted Fantasy in Hawaii. Released Runaway and the GOOD Fridays series. Collaborated with Jay-Z on Watch the Throne. Expanded the GOOD Music collective with Cruel Summer.",
    },
    albumIds: ["mbdtf", "watch-the-throne", "cruel-summer"],
  },
  {
    id: "yeezus-fashion",
    range: "2013 – 2015",
    title: { zh: "Yeezus & Fashion", en: "Yeezus & Fashion" },
    body: {
      zh: "Yeezus 引入了刺耳的工业极简声音。扩展到建筑、时尚和产品设计。发展了 Yeezy 视觉身份和时尚方向。黑色极简美学成为他作品的核心。",
      en: "Yeezus introduced a harsh industrial minimalist sound. Expanded into architecture, fashion, and product design. Developed the Yeezy visual identity and fashion direction. Minimal black aesthetics became central to his work.",
    },
    albumIds: ["yeezus"],
  },
  {
    id: "pablo",
    range: "2016 – 2017",
    title: { zh: "The Life of Pablo", en: "The Life of Pablo" },
    body: {
      zh: "通过不断演变的公众发布方式发行 The Life of Pablo。专辑融合了福音、互联网文化和极繁主义。Saint Pablo Tour 采用了悬浮舞台概念。这个时期以公众不稳定性和巡演取消告终。",
      en: "Released The Life of Pablo through an evolving public rollout. The album blended gospel, internet culture, and maximalism. The Saint Pablo Tour featured a floating stage concept. This period ended with public instability and tour cancellation.",
    },
    albumIds: ["life-of-pablo"],
  },
  {
    id: "wyoming",
    range: "2018 – 2019",
    title: { zh: "Wyoming Sessions", en: "Wyoming Sessions" },
    body: {
      zh: "在怀俄明州制作多张专辑。发行 Ye 和 Kids See Ghosts。为 Nas、Pusha T 和 Teyana Taylor 制作项目。主题包括孤立、心理健康和重塑。",
      en: "Produced multiple albums in Wyoming. Released Ye and Kids See Ghosts. Produced projects for Nas, Pusha T, and Teyana Taylor. Themes included isolation, mental health, and reinvention.",
    },
    albumIds: ["ye", "kids-see-ghosts"],
  },
  {
    id: "faith-era",
    range: "2019 – 2022",
    title: { zh: "Jesus Is King / Donda", en: "Jesus Is King / Donda" },
    body: {
      zh: "发起 Sunday Service 演出。2019 年发行 Jesus Is King。通过大规模体育场试听活动创作 Donda。这个时代聚焦于悲伤、信仰、极简主义和表演奇观。",
      en: "Launched Sunday Service performances. Released Jesus Is King in 2019. Created Donda through large-scale stadium listening events. This era focused on grief, faith, minimalism, and performance spectacle.",
    },
    albumIds: ["jesus-is-king", "donda", "donda-2"],
  },
  {
    id: "current-era",
    range: "2023 – Present",
    title: { zh: "Vultures / Current Era", en: "Vultures / Current Era" },
    body: {
      zh: "与 Ty Dolla Sign 合作组成 ¥$。2024 年发行 Vultures 1。公众形象变得越来越有争议和碎片化。将这个时代呈现为一个未完成的篇章。",
      en: "Collaborated with Ty Dolla Sign as ¥$. Released Vultures 1 in 2024. Public image became increasingly controversial and fragmented. Present this era neutrally as an unfinished chapter.",
    },
    albumIds: ["vultures-1", "vultures-2", "bully"],
  },
];
